/**
 * @file Version.h
 * @brief Version information for INA228.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef INA228_VERSION_STRING
/// @brief Semantic version string; may be overridden by the build.
#define INA228_VERSION_STRING "3.0.2"
#endif

#ifndef INA228_BUILD_DATE
/// @brief Build date string; defaults to the compiler date.
#define INA228_BUILD_DATE __DATE__
#endif

#ifndef INA228_BUILD_TIME
/// @brief Build time string; defaults to the compiler time.
#define INA228_BUILD_TIME __TIME__
#endif

#ifndef INA228_BUILD_TIMESTAMP
/// @brief Combined build date and time string.
#define INA228_BUILD_TIMESTAMP INA228_BUILD_DATE " " INA228_BUILD_TIME
#endif

#ifndef INA228_GIT_COMMIT
/// @brief Source commit identifier supplied by the build when available.
#define INA228_GIT_COMMIT "unknown"
#endif

#ifndef INA228_GIT_STATUS
/// @brief Source worktree state supplied by the build when available.
#define INA228_GIT_STATUS "unknown"
#endif

#ifndef INA228_VERSION_FULL
/// @brief Version string combined with commit, timestamp, and worktree state.
#define INA228_VERSION_FULL INA228_VERSION_STRING " (" INA228_GIT_COMMIT ", " INA228_BUILD_TIMESTAMP ", " INA228_GIT_STATUS ")"
#endif

/// @brief Version and build metadata constants for INA228.
namespace INA228 {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 3;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 0;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 2;

/// @brief Full semantic version string.
static constexpr const char* VERSION = INA228_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 30002;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 30002;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = INA228_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = INA228_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = INA228_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = INA228_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = INA228_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = INA228_VERSION_FULL;

}  // namespace INA228
