if(NOT DEFINED INA228_REPO_ROOT OR NOT DEFINED INA228_PROVENANCE_HEADER)
  message(FATAL_ERROR "INA228 provenance paths were not supplied")
endif()

set(INA228_EXAMPLE_GIT_COMMIT "unknown")
set(INA228_EXAMPLE_GIT_STATUS "unknown")

if(DEFINED INA228_GIT_EXECUTABLE AND
   NOT INA228_GIT_EXECUTABLE STREQUAL "" AND
   EXISTS "${INA228_GIT_EXECUTABLE}")
  execute_process(
    COMMAND "${INA228_GIT_EXECUTABLE}" rev-parse --short=12 HEAD
    WORKING_DIRECTORY "${INA228_REPO_ROOT}"
    RESULT_VARIABLE INA228_GIT_COMMIT_RESULT
    OUTPUT_VARIABLE INA228_GIT_COMMIT_OUTPUT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
  )
  execute_process(
    COMMAND "${INA228_GIT_EXECUTABLE}" status --porcelain --untracked-files=normal
    WORKING_DIRECTORY "${INA228_REPO_ROOT}"
    RESULT_VARIABLE INA228_GIT_STATUS_RESULT
    OUTPUT_VARIABLE INA228_GIT_STATUS_OUTPUT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
  )

  string(LENGTH "${INA228_GIT_COMMIT_OUTPUT}" INA228_GIT_COMMIT_LENGTH)
  if(INA228_GIT_COMMIT_RESULT EQUAL 0 AND
     INA228_GIT_STATUS_RESULT EQUAL 0 AND
     INA228_GIT_COMMIT_LENGTH EQUAL 12 AND
     INA228_GIT_COMMIT_OUTPUT MATCHES "^[0-9a-fA-F]+$")
    string(TOLOWER "${INA228_GIT_COMMIT_OUTPUT}" INA228_EXAMPLE_GIT_COMMIT)
    set(INA228_EXAMPLE_GIT_STATUS "clean")
    if(NOT INA228_GIT_STATUS_OUTPUT STREQUAL "")
      set(INA228_EXAMPLE_GIT_STATUS "dirty")
    endif()
  endif()
endif()

set(INA228_PROVENANCE_CONTENT
    "#pragma once\n#define INA228_GIT_COMMIT \"${INA228_EXAMPLE_GIT_COMMIT}\"\n#define INA228_GIT_STATUS \"${INA228_EXAMPLE_GIT_STATUS}\"\n")
set(INA228_PROVENANCE_TEMP "${INA228_PROVENANCE_HEADER}.tmp")
file(WRITE "${INA228_PROVENANCE_TEMP}" "${INA228_PROVENANCE_CONTENT}")
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E copy_if_different
          "${INA228_PROVENANCE_TEMP}" "${INA228_PROVENANCE_HEADER}"
  RESULT_VARIABLE INA228_PROVENANCE_COPY_RESULT
)
file(REMOVE "${INA228_PROVENANCE_TEMP}")
if(NOT INA228_PROVENANCE_COPY_RESULT EQUAL 0)
  message(FATAL_ERROR "Failed to update ${INA228_PROVENANCE_HEADER}")
endif()
